--+up BEGIN
CREATE TABLE IF NOT EXISTS TASKS
(
	TASK_GROUP_ID BIGINT DEFAULT 0,
  STATE VARCHAR(100) NO NULL,
  PRIMARY KEY (ID)
) INHERITS (BASE_TABLE);

CREATE TABLE IF NOT EXISTS TASK_GROUPS
(
  STATE VARCHAR(100) NO NULL,
  PRIMARY KEY (ID)
) INHERITS (BASE_TABLE);

CREATE TRIGGER T_CREATED BEFORE INSERT ON TASKS FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER T_UPDATED BEFORE UPDATE ON TASKS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();

CREATE TRIGGER TG_CREATED BEFORE INSERT ON TASK_GROUPS FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER TG_UPDATED BEFORE UPDATE ON TASK_GROUPS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();
--+up END

--+down BEGIN
DROP TRIGGER IF EXISTS TG_CREATED ON TASK_GROUPS;
DROP TRIGGER IF EXISTS TG_UPDATED ON TASK_GROUPS;

DROP TRIGGER IF EXISTS T_CREATED ON TASKS;
DROP TRIGGER IF EXISTS T_UPDATED ON TASKS;

DROP TABLE IF EXISTS TASK_GROUPS;
DROP TABLE IF EXISTS TASKS;
--+down END
