--+up BEGIN
CREATE TABLE IF NOT EXISTS EQUIPMENTS
(
  STATE VARCHAR(100) NO NULL,
  PRIMARY KEY (ID)
) INHERITS (BASE_TABLE);

CREATE TABLE IF NOT EXISTS EQUIPMENT_SLOTS
(
	STATE VARCHAR(100) NO NULL,
  PRIMARY KEY (ID)
) INHERITS (BASE_TABLE);

CREATE TRIGGER E_CREATED BEFORE INSERT ON EQUIPMENTS FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER E_UPDATED BEFORE UPDATE ON EQUIPMENTS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();

CREATE TRIGGER ES_CREATED BEFORE INSERT ON EQUIPMENT_SLOTS FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER ES_UPDATED BEFORE UPDATE ON EQUIPMENT_SLOTS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();
--+up END

--+down BEGIN
DROP TRIGGER IF EXISTS ES_CREATED ON EQUIPMENT_SLOTS;
DROP TRIGGER IF EXISTS ES_CREATED ON EQUIPMENT_SLOTS;

DROP TRIGGER IF EXISTS E_CREATED ON EQUIPMENTS;
DROP TRIGGER IF EXISTS E_UPDATED ON EQUIPMENTS;

DROP TABLE IF EXISTS EQUIPMENT_SLOTS;
DROP TABLE IF EXISTS EQUIPMENTS;
--+down END
