--+up BEGIN
CREATE TABLE IF NOT EXISTS OPERATORS
(
  STATE VARCHAR(100) NO NULL,
  PRIMARY KEY (ID)
) INHERITS (BASE_TABLE);

CREATE TABLE IF NOT EXISTS OPERATOR_METADATA
(
  PRIMARY KEY (ID)
) INHERITS (BASE_METADATA_TABLE);

CREATE TABLE IF NOT EXISTS OPERATOR_ACTIVITIES
(
  PRIMARY KEY (ID)
) INHERITS (BASE_TABLE);

CREATE TRIGGER OPS_CREATED BEFORE INSERT ON OPERATORS FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER OPS_UPDATED BEFORE UPDATE ON OPERATORS FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();

CREATE TRIGGER OPSM_CREATED BEFORE INSERT ON OPERATOR_METADATA FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER OPSM_UPDATED BEFORE UPDATE ON OPERATOR_METADATA FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();

CREATE TRIGGER OPSA_CREATED BEFORE INSERT ON OPERATOR_ACTIVITIES FOR EACH ROW EXECUTE PROCEDURE INIT_TIME_ON_CREATED();
CREATE TRIGGER OPSA_UPDATED BEFORE UPDATE ON OPERATOR_ACTIVITIES FOR EACH ROW EXECUTE PROCEDURE UPDATE_TIME_ON_UPDATED();
--+up END

--+down BEGIN
DROP TRIGGER IF EXISTS OPSA_CREATED ON OPERATOR_ACTIVITIES;
DROP TRIGGER IF EXISTS OPSA_UPDATED ON OPERATOR_ACTIVITIES;

DROP TRIGGER IF EXISTS OPSM_CREATED ON OPERATOR_METADATA;
DROP TRIGGER IF EXISTS OPSM_UPDATED ON OPERATOR_METADATA;

DROP TRIGGER IF EXISTS OPS_CREATED ON OPERATORS;
DROP TRIGGER IF EXISTS OPS_UPDATED ON OPERATORS;

DROP TABLE IF EXISTS OPERATOR_ACTIVITIES;
DROP TABLE IF EXISTS OPERATOR_METADATA;
DROP TABLE IF EXISTS OPERATORS;
--+down END
